/** Writes docs/cli.md from src/core/cli-guide.ts, so the committed doc and
 *  `agentbox guide` are one text. Run: `bun run docs:cli`. */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { CLI_GUIDE } from "../src/core/cli-guide";

const header = `<!-- Generated by \`bun run docs:cli\` from src/core/cli-guide.ts; edit there. The same text is what \`agentbox guide\` prints. -->

# The agentbox CLI, for agents

`;

const here = new URL("..", import.meta.url).pathname;
writeFileSync(join(here, "docs", "cli.md"), header + CLI_GUIDE);
console.log("wrote docs/cli.md");
